export const buildAuditHTML = (audit: any) => {
  const tools = audit?.tools || [];

  return `
  <html>
    <body style="font-family: Arial; padding: 40px; color: #111;">
      
      <h1 style="font-size: 32px;">
        AI Spend Audit Report
      </h1>

      <p style="color: gray;">
        Optimized AI subscription analysis
      </p>

      <div style="background:#f3f4f6;padding:20px;border-radius:12px;margin-top:30px;">
        <h2>Summary</h2>
        <p>${audit.summary}</p>
      </div>

      <div style="margin-top:30px;">
        <h2 style="color:green;">
          Total Savings: $${audit.total_savings}/month
        </h2>
      </div>

      <table 
        style="width:100%;border-collapse:collapse;margin-top:30px;"
      >
        <tr style="background:#111;color:white;">
          <th style="padding:12px;">Tool</th>
          <th style="padding:12px;">Plan</th>
          <th style="padding:12px;">Cost</th>
          <th style="padding:12px;">Use Case</th>
        </tr>

        ${tools
          .map(
            (tool: any) => `
          <tr>
            <td style="padding:12px;border-bottom:1px solid #ddd;">
              ${tool.name}
            </td>

            <td style="padding:12px;border-bottom:1px solid #ddd;">
              ${tool.plan}
            </td>

            <td style="padding:12px;border-bottom:1px solid #ddd;">
              $${tool.cost}
            </td>

            <td style="padding:12px;border-bottom:1px solid #ddd;">
              ${tool.useCase}
            </td>
          </tr>
        `
          )
          .join("")}
      </table>

      <p style="margin-top:40px;color:gray;font-size:12px;">
        Generated by AI Spend Audit
      </p>

    </body>
  </html>
  `;
};