"use client";

import { use, useEffect, useState } from "react";
import { supabase } from "@/src/lib/supabaseClient";

type Tool = {
  name: string;
  plan: string;
  cost: string;
  teamSize: string;
  useCase: string;
};

type Audit = {
  id: string;
  summary: string;
  total_savings: number;
  tools: Tool[];
};

export default function AuditPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);

  const [audit, setAudit] = useState<Audit | null>(null);

  useEffect(() => {
    async function fetchAudit() {
      const { data, error } = await supabase
        .from("audits")
        .select("*")
        .eq("id", id)
        .single();

      if (error) {
        console.error(error);
        return;
      }

      setAudit(data);
    }

    fetchAudit();
  }, [id]);

  const downloadPDF = async () => {
    if (!audit) return;

    const jsPDF = (await import("jspdf")).default;

    const doc = new jsPDF();

    // HEADER
    doc.setFontSize(24);
    doc.text("AI Spend Audit Report", 20, 20);

    doc.setFontSize(12);
    doc.text("Optimized AI subscription analysis", 20, 30);

    // SUMMARY
    doc.setFontSize(18);
    doc.text("Summary", 20, 50);

    doc.setFontSize(11);

    doc.text(
      audit.summary || "No summary available",
      20,
      60,
      {
        maxWidth: 170,
      }
    );

    // SAVINGS
    doc.setFontSize(18);

    doc.text(
      `Total Savings: $${audit.total_savings || 0}/month`,
      20,
      95
    );

    doc.setFontSize(14);

    doc.text(
      `$${(audit.total_savings || 0) * 12}/year`,
      20,
      108
    );

    // TOOLS
    let y = 130;

    doc.setFontSize(18);
    doc.text("Tools Breakdown", 20, y);

    y += 12;

    audit.tools?.forEach((tool) => {
      doc.setFontSize(11);

      doc.text(
        `${tool.name} | ${tool.plan} | $${tool.cost}/mo | ${tool.useCase}`,
        20,
        y
      );

      y += 10;
    });

    // FOOTER
    doc.setFontSize(10);

    doc.text(
      "Generated by AI Spend Audit",
      20,
      280
    );

    doc.save("ai-spend-audit.pdf");
  };

  const sendEmail = async () => {
    if (!audit) return;

    const email = prompt("Enter email address");

    if (!email) return;

    const res = await fetch("/api/email", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        email,
        audit,
      }),
    });

    if (res.ok) {
      alert("Email sent successfully!");
    } else {
      alert("Failed to send email");
    }
  };

  if (!audit) {
    return (
      <div className="min-h-screen bg-black text-white flex items-center justify-center">
        Loading audit...
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-black text-white p-10">

      <div className="max-w-4xl mx-auto">

        {/* HEADER */}
        <h1 className="text-6xl font-extrabold mb-4">
          AI Spend Audit Report
        </h1>

        <p className="text-gray-400 mb-10">
          Optimized AI subscription analysis report
        </p>

        {/* SAVINGS CARD */}
        <div className="bg-green-500 text-black p-8 rounded-3xl mb-10">

          <h2 className="text-3xl font-bold mb-3">
            Total Savings
          </h2>

          <p className="text-5xl font-extrabold">
            ${audit.total_savings || 0}/month
          </p>

          <p className="text-2xl mt-3">
            ${(audit.total_savings || 0) * 12}/year
          </p>

        </div>

        {/* SUMMARY */}
        <div className="bg-gray-900 border border-gray-700 p-6 rounded-2xl mb-10">

          <h2 className="text-3xl font-bold mb-4">
            Summary
          </h2>

          <p className="text-gray-300 leading-8">
            {audit.summary || "No summary available"}
          </p>

        </div>

        {/* TOOLS */}
        <div className="space-y-5">

          <h2 className="text-3xl font-bold mb-4">
            Tools Breakdown
          </h2>

          {audit.tools?.map((tool, index) => (
            <div
              key={index}
              className="bg-gray-900 border border-gray-700 p-5 rounded-2xl"
            >

              <p className="mb-2">
                <span className="font-bold">
                  Tool:
                </span>{" "}
                {tool.name}
              </p>

              <p className="mb-2">
                <span className="font-bold">
                  Plan:
                </span>{" "}
                {tool.plan}
              </p>

              <p className="mb-2">
                <span className="font-bold">
                  Monthly Cost:
                </span>{" "}
                ${tool.cost}
              </p>

              <p className="mb-2">
                <span className="font-bold">
                  Team Size:
                </span>{" "}
                {tool.teamSize}
              </p>

              <p>
                <span className="font-bold">
                  Use Case:
                </span>{" "}
                {tool.useCase}
              </p>

            </div>
          ))}

        </div>

        {/* BUTTONS */}
        <div className="flex gap-4 mt-10">

          <button
            onClick={downloadPDF}
            className="bg-green-500 text-black px-6 py-3 rounded-xl font-bold cursor-pointer hover:bg-green-400"
          >
            Download PDF
          </button>

          <button
            onClick={sendEmail}
            className="bg-blue-500 px-6 py-3 rounded-xl font-bold cursor-pointer hover:bg-blue-400"
          >
            Send Email
          </button>

        </div>

      </div>

    </div>
  );
}